# This is a basic workflow to help you get started with Actions

name: generate animation

# Controls when the workflow will run
on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    permissions: 
      contents: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # generates a snake game from a github user (karanrjhaveri) contributions graph, output a svg animation at dist/github-contribution-grid-snake.svg & dist/github-contribution-grid-snake-dark.svg
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: karanrjhaveri
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
          
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/karanrjhaveri/karanrjhaveri/main/dist/github-contribution-grid-snake.svg , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
